// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
import Amplify from 'aws-amplify';
import * as WebBrowser from 'expo-web-browser';
import {Linking, Platform} from 'react-native'

const urlOpener = async (url, redirectUrl) => {
    // On Expo, use WebBrowser.openAuthSessionAsync to open the Hosted UI pages.
    const { type, url: newUrl } = await WebBrowser.openAuthSessionAsync(url, redirectUrl);
    if (type === 'success') {
        await WebBrowser.dismissBrowser();

        if (Platform.OS === 'ios') {
        console.log(url)
        return Linking.openURL(newUrl);
        }
    } 
};

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:7e42a0d2-b901-4cd1-8154-be6cc20ac75c",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_0KFVM746Z",
    "aws_user_pools_web_client_id": "6t8b52kvsst5ln43sni3vkeovh",
    "oauth": {
        "domain": "wazifa-auth-dev.auth.eu-central-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://192.168.65.142:19000/",
        "redirectSignOut": "exp://192.168.65.142:19000/",
        "responseType": "code",
        urlOpener
    },
    "federationTarget": "COGNITO_USER_POOLS",


};


export default awsmobile;