export const GET_JOBS = 'GET_JOBS';
export const GET_JOBS_FULFILLED = 'GET_JOBS_FULFILLED';
export const GET_JOBS_REJECTED = 'GET_JOBS_REJECTED'

export const ADD_NEW_JOB_REQUEST = 'ADD_NEW_JOB_REQUEST';
export const ADD_NEW_JOB_REQUEST_FULFILLED = 'ADD_NEW_JOB_REQUEST_FULFILLED';
export const ADD_NEW_JOB_REQUEST_REJECTED = 'ADD_NEW_JOB_REQUEST_REJECTED'


